# Generated by Django 3.2.7 on 2021-09-03 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0002_alter_follow_account_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='account_id',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='follower_id',
            new_name='follower',
        ),
    ]
